/**
 * MetadataFieldsEditor — editorial metadata fields for a sequence.
 *
 * A sequence's metadata fields and a transition's capture inputs are the same
 * object at different scopes — a named, typed, optionally-required place to put
 * a value — so both are `InspectorFieldList`, and all that lives here is what
 * makes a metadata field a metadata field: its type options, its config form,
 * and what a new one starts as.
 *
 * That replaces a stack of `Card`s, one open sub-form per field, which turned a
 * sequence carrying half a dozen fields into a wall of controls with no way to
 * see the list's shape — and which had no order at all, since nothing offered to
 * change it. The list is now the surface, one field's options open at a time,
 * and the order is the author's to drag.
 *
 * @package
 */

import {
	TextControl,
	TextareaControl,
	SelectControl,
	ToggleControl,
} from '@wordpress/components';
import { Stack } from '@wordpress/ui';
import { __ } from '@wordpress/i18n';
import { sanitizeMetadataKey } from '../../utils/metadata-keys';
import InspectorFieldList, {
	InspectorFieldListAdd,
} from './InspectorFieldList';

const FIELD_TYPES = [
	{ label: __( 'Text', 'vip-workflow' ), value: 'text' },
	{ label: __( 'Text area', 'vip-workflow' ), value: 'textarea' },
	{ label: __( 'Select', 'vip-workflow' ), value: 'select' },
	{ label: __( 'Date', 'vip-workflow' ), value: 'date' },
	{ label: __( 'User', 'vip-workflow' ), value: 'user' },
];

/**
 * Name a field's type, including one this build cannot author.
 *
 * A type registered by an extension, or one a newer version wrote, still has to
 * read back as itself in the list rather than as a blank.
 *
 * @param {string} type The field's stored type.
 * @return {string} A human-readable name for it.
 */
function fieldTypeLabel( type ) {
	return FIELD_TYPES.find( ( t ) => t.value === type )?.label || type;
}

/**
 * The key a label change implies.
 *
 * The key follows the label until someone types a key of their own; from then on
 * it is theirs and renaming the field leaves it alone.
 *
 * @param {Object} field The field being renamed.
 * @param {string} label Its new label.
 * @return {string} The key the field should now carry.
 */
function keyForLabelChange( field, label ) {
	if ( field.keyAutoGenerated === false ) {
		return field.key || '';
	}
	if ( field.keyAutoGenerated || ! field.key ) {
		return sanitizeMetadataKey( label );
	}
	return field.key;
}

/**
 * A new metadata field.
 *
 * Deliberately blank rather than pre-named. The key is generated from the label,
 * so there is nothing to auto-generate until the author has said what the field
 * is — and `InspectorFieldList` will not flag an unnamed row as missing its key
 * for exactly that reason.
 *
 * @return {Object} The new field.
 */
function createField() {
	return {
		key: '',
		label: '',
		type: 'text',
		required: false,
		searchable: false,
		keyAutoGenerated: true,
	};
}

/**
 * The Add control for the metadata field list, for a section's `actions` slot.
 *
 * @param {Object}   props          Component props.
 * @param {Array}    props.fields   The current fields.
 * @param {Function} props.onChange Reports the whole list back.
 * @return {JSX.Element} The add control.
 */
export function MetadataFieldsAdd( { fields, onChange } ) {
	return (
		<InspectorFieldListAdd
			addOptions={ [
				{ label: __( 'Field', 'vip-workflow' ), value: 'field' },
			] }
			onAdd={ () => onChange( [ ...fields, createField() ] ) }
			label={ __( 'Add field', 'vip-workflow' ) }
		/>
	);
}

export default function MetadataFieldsEditor( { fields, onChange } ) {
	return (
		<InspectorFieldList
			items={ fields }
			onChange={ onChange }
			keyOf={ ( field ) => field.key || '' }
			// A field the author has named is one they have started, so a key
			// they then cleared by hand is a state someone chose and Save will
			// refuse. A row added a moment ago and not yet typed into is
			// incomplete rather than wrong.
			isStarted={ ( field ) => Boolean( field.label ) }
			describe={ ( field ) => ( {
				label: field.label || __( 'Untitled', 'vip-workflow' ),
				value: fieldTypeLabel( field.type ),
			} ) }
			renderConfig={ ( { item: field, update, problem } ) => (
				<>
					<TextControl
						__next40pxDefaultSize
						__nextHasNoMarginBottom
						label={ __( 'Field label', 'vip-workflow' ) }
						value={ field.label }
						onChange={ ( label ) =>
							update( {
								label,
								key: keyForLabelChange( field, label ),
							} )
						}
					/>
					<TextControl
						__next40pxDefaultSize
						__nextHasNoMarginBottom
						label={ __( 'Key', 'vip-workflow' ) }
						value={ field.key }
						onChange={ ( v ) =>
							update( {
								key: sanitizeMetadataKey( v ),
								keyAutoGenerated: false,
							} )
						}
						placeholder="content_pillar"
						className={
							problem ? 'wf-metadata-field__key--invalid' : ''
						}
						help={ problem?.full }
					/>
					<SelectControl
						__next40pxDefaultSize
						__nextHasNoMarginBottom
						label={ __( 'Type', 'vip-workflow' ) }
						value={ field.type }
						options={ FIELD_TYPES }
						onChange={ ( type ) => update( { type } ) }
					/>
					{ field.type === 'select' && (
						<TextareaControl
							__nextHasNoMarginBottom
							label={ __( 'Options', 'vip-workflow' ) }
							value={ ( field.options || [] ).join( '\n' ) }
							onChange={ ( v ) =>
								update( { options: v.split( '\n' ) } )
							}
							help={ __( 'One option per line', 'vip-workflow' ) }
							rows={ 3 }
						/>
					) }
					<Stack
						direction="row"
						gap="lg"
						align="flex-start"
						justify="flex-start"
					>
						<ToggleControl
							__nextHasNoMarginBottom
							label={ __( 'Required', 'vip-workflow' ) }
							checked={ Boolean( field.required ) }
							onChange={ ( required ) => update( { required } ) }
						/>
						<ToggleControl
							__nextHasNoMarginBottom
							label={ __( 'Searchable', 'vip-workflow' ) }
							checked={ Boolean( field.searchable ) }
							onChange={ ( searchable ) =>
								update( { searchable } )
							}
						/>
					</Stack>
				</>
			) }
			removeLabel={ __( 'Remove field', 'vip-workflow' ) }
			emptyLabel={ __(
				'This sequence has no metadata fields. Add one to collect a value alongside every post that travels it.',
				'vip-workflow'
			) }
		/>
	);
}
